apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: springboot-app
type: Opaque
stringData:
  root-password: "RootPassword123!"
  database: "springboot_test"
  username: "helmi_user"
  password: "Helmi@2025"
